<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `speech_assets` (MODERNIZATION_PLAN §6.3, §9). Same raw/driver-branched
     * approach as the `speeches` migration and for the same reason: the
     * `kind`↔`format` CHECK and the partial-unique "one primary asset per
     * kind" index have no Blueprint equivalent, and SQLite (the test-suite
     * driver) can only pick up a CHECK constraint at CREATE TABLE time.
     *
     * `kind` is deliberately just `source|video|captions` here — §9.5's
     * `poster`/`sprite`/`voice_note` kinds are a later, additive ALTER
     * (§12.1: "run the ALTER late"), not needed until S4/S9/S10.
     *
     * `format` widens the base table's `mp4|hls|vtt` with `mov`: an
     * uploaded iPhone source is stored as a `kind=source` row *before* the
     * transcoder has run, and its real container is QuickTime — recording
     * it as `mp4` would be a lie the failure surface (STEP-03's explicit
     * "an unmodified iPhone .MOV fails visibly") depends on being accurate.
     *
     * `upload_id` and `client_declared_bytes` are multipart-upload
     * bookkeeping this step's presign/complete/abort endpoints need and the
     * plan's table doesn't itemize: `client_declared_bytes` is the
     * untrusted size the client reported at `create`, kept only so
     * completion can reconcile the quota by the delta against the real
     * `byte_size` (§9.1) — never trusted for anything else.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE speech_assets (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    speech_id INTEGER NOT NULL,
                    kind VARCHAR(16) NOT NULL,
                    format VARCHAR(8) NOT NULL,
                    rendition VARCHAR(16) NULL,
                    disk VARCHAR(32) NOT NULL DEFAULT 'media',
                    path VARCHAR(255) NOT NULL,
                    original_filename VARCHAR(255) NULL,
                    mime_type VARCHAR(255) NULL,
                    byte_size BIGINT NULL,
                    duration_seconds NUMERIC(10, 3) NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'uploading',
                    failure_code VARCHAR(64) NULL,
                    failure_detail VARCHAR(2000) NULL,
                    is_primary TINYINT(1) NOT NULL DEFAULT 0,
                    upload_id VARCHAR(255) NULL,
                    client_declared_bytes BIGINT NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_speech_assets_kind
                        CHECK (kind IN ('source', 'video', 'captions')),
                    CONSTRAINT ck_speech_assets_format
                        CHECK (format IN ('mp4', 'mov', 'hls', 'vtt')),
                    CONSTRAINT ck_speech_assets_status
                        CHECK (status IN ('uploading', 'processing', 'ready', 'failed')),
                    CONSTRAINT ck_speech_assets_kind_format
                        CHECK (
                            (kind = 'source' AND format IN ('mp4', 'mov'))
                            OR (kind = 'video' AND format IN ('mp4', 'hls'))
                            OR (kind = 'captions' AND format = 'vtt')
                        ),
                    FOREIGN KEY (speech_id) REFERENCES speeches (id) ON DELETE CASCADE
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE speech_assets (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    speech_id BIGINT NOT NULL REFERENCES speeches (id) ON DELETE CASCADE,
                    kind VARCHAR(16) NOT NULL,
                    format VARCHAR(8) NOT NULL,
                    rendition VARCHAR(16) NULL,
                    disk VARCHAR(32) NOT NULL DEFAULT 'media',
                    path VARCHAR(255) NOT NULL,
                    original_filename VARCHAR(255) NULL,
                    mime_type VARCHAR(255) NULL,
                    byte_size BIGINT NULL,
                    duration_seconds NUMERIC(10, 3) NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'uploading',
                    failure_code VARCHAR(64) NULL,
                    failure_detail VARCHAR(2000) NULL,
                    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
                    upload_id VARCHAR(255) NULL,
                    client_declared_bytes BIGINT NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_speech_assets_kind
                        CHECK (kind IN ('source', 'video', 'captions')),
                    CONSTRAINT ck_speech_assets_format
                        CHECK (format IN ('mp4', 'mov', 'hls', 'vtt')),
                    CONSTRAINT ck_speech_assets_status
                        CHECK (status IN ('uploading', 'processing', 'ready', 'failed')),
                    CONSTRAINT ck_speech_assets_kind_format
                        CHECK (
                            (kind = 'source' AND format IN ('mp4', 'mov'))
                            OR (kind = 'video' AND format IN ('mp4', 'hls'))
                            OR (kind = 'captions' AND format = 'vtt')
                        )
                )
                SQL);
        }

        DB::statement('CREATE INDEX speech_assets_speech_id_index ON speech_assets (speech_id)');
        DB::statement('CREATE UNIQUE INDEX uq_assets_primary ON speech_assets (speech_id, kind) WHERE is_primary');
    }

    public function down(): void
    {
        Schema::dropIfExists('speech_assets');
    }
};
