<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `connections` — STEP-13-FROZEN-CONTRACT.md §3 / MODERNIZATION_PLAN
     * §6.7.2. Same driver-branched raw-SQL shape as `coach_applications`
     * (2026_08_22_100001_create_coach_applications_table.php): `state` is
     * CHECK-enumerated (sqlite, the test-suite driver, can only acquire a
     * CHECK constraint at CREATE TABLE time).
     *
     * **Two mirrored rows, not one canonical `(LEAST, GREATEST)` row** — see
     * §6.7.2's own reasoning: mirrored gives
     * `WHERE owner_id=:me AND state='accepted' ORDER BY connected_at DESC, id DESC`,
     * a pure index range scan, at the cost of a transactional double-write
     * every write path (App\Services\ConnectionService) must keep in sync,
     * always lower-user-id-first to avoid the AB-BA deadlock. A nightly
     * reconciler (App\Console\Commands\ReconcileConnectionAsymmetryCommand)
     * catches any pair that falls out of sync anyway.
     *
     * `initiated_by_id`/`blocked_by_id` carry the SAME value on both
     * mirrored rows (they name a person, viewed from either side) — mirrored
     * like `owner_id`/`peer_id` would let the two rows disagree about who
     * asked/blocked.
     *
     * No `deleted_at` — identical reasoning to `reviews`/`speeches`: a
     * soft-deleted row still holds `(owner_id, peer_id)`, so reconnecting
     * throws a duplicate key. `declined` is the state that means "not
     * connected". Erasure deletes these rows outright (§6.7.2's own note,
     * unlike reviews) — that's a future step's concern, not this migration's.
     *
     * CHECK constraint names use the FULL table name, never an abbreviation
     * (`ck_connections_*`, not `ck_conn_*`) — STEP-13-FROZEN-CONTRACT.md §3's
     * correction to §6.7.2's literal text, matching every other CHECK name
     * in this schema (`ck_speech_assets_kind`, `ck_coach_applications_status`,
     * `ck_reviews_status`, …).
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE connections (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    owner_id INTEGER NOT NULL,
                    peer_id INTEGER NOT NULL,
                    state VARCHAR(16) NOT NULL DEFAULT 'pending',
                    initiated_by_id INTEGER NULL,
                    blocked_by_id INTEGER NULL,
                    requested_at DATETIME NULL,
                    responded_at DATETIME NULL,
                    connected_at DATETIME NULL,
                    note VARCHAR(280) NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_connections_no_self
                        CHECK (owner_id <> peer_id),
                    CONSTRAINT ck_connections_initiator
                        CHECK (initiated_by_id IS NULL OR initiated_by_id IN (owner_id, peer_id)),
                    CONSTRAINT ck_connections_blocker
                        CHECK (blocked_by_id IS NULL OR blocked_by_id IN (owner_id, peer_id)),
                    CONSTRAINT ck_connections_blocked
                        CHECK (state <> 'blocked' OR blocked_by_id IS NOT NULL),
                    CONSTRAINT ck_connections_state
                        CHECK (state IN ('pending', 'accepted', 'declined', 'blocked')),
                    FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE,
                    FOREIGN KEY (peer_id) REFERENCES users (id) ON DELETE CASCADE,
                    FOREIGN KEY (initiated_by_id) REFERENCES users (id) ON DELETE SET NULL,
                    FOREIGN KEY (blocked_by_id) REFERENCES users (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE connections (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    owner_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    peer_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    state VARCHAR(16) NOT NULL DEFAULT 'pending',
                    initiated_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    blocked_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    requested_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    responded_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    connected_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    note VARCHAR(280) NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_connections_no_self
                        CHECK (owner_id <> peer_id),
                    CONSTRAINT ck_connections_initiator
                        CHECK (initiated_by_id IS NULL OR initiated_by_id IN (owner_id, peer_id)),
                    CONSTRAINT ck_connections_blocker
                        CHECK (blocked_by_id IS NULL OR blocked_by_id IN (owner_id, peer_id)),
                    CONSTRAINT ck_connections_blocked
                        CHECK (state <> 'blocked' OR blocked_by_id IS NOT NULL),
                    CONSTRAINT ck_connections_state
                        CHECK (state IN ('pending', 'accepted', 'declined', 'blocked'))
                )
                SQL);
        }

        DB::statement('CREATE UNIQUE INDEX uq_connections_owner_peer ON connections (owner_id, peer_id)');
        // The list — no filesort (§6.7.2).
        DB::statement('CREATE INDEX ix_connections_owner_state_connected ON connections (owner_id, state, connected_at, id)');
        // Inbox / sent.
        DB::statement('CREATE INDEX ix_connections_owner_state_requested ON connections (owner_id, state, requested_at, id)');
        // Reconciler, admin, mutuals.
        DB::statement('CREATE INDEX ix_connections_peer_state ON connections (peer_id, state)');
    }

    public function down(): void
    {
        Schema::dropIfExists('connections');
    }
};
