<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `speech_transcripts` (STEP-09-captions.md §6.12, the frozen STEP-09
     * backend contract §7/§8). One row per speech, derived from that
     * speech's canonical `captions` VTT asset — never the other way
     * around (STEP-09.md: "the VTT stays canonical; the table is
     * derived... never write back the other way").
     *
     * Same raw/driver-branched approach as `speech_assets`/`speeches`, for
     * the same reason: `source` is a Postgres CHECK constraint
     * (`whisper`/`edited`), mirroring the `speech_assets.kind`/`format`
     * CHECK convention exactly rather than a free-text column, and SQLite
     * (the test-suite driver) can only pick up a CHECK constraint at
     * CREATE TABLE time.
     *
     * The Postgres branch additionally carries a GENERATED `tsvector`
     * column over `body` plus a GIN index (§7 of the frozen contract:
     * "the Postgres branch creates a generated tsvector column + GIN
     * index"). SQLite gets a plain column with no index — full-text search
     * falls back to `LIKE` there (§7: "adequate for a test fixture with a
     * handful of rows, not a testing-strategy gap in practice"). Because a
     * SQLite CREATE TABLE can't express a generated tsvector column at
     * all, the sqlite branch simply omits the column outright — the
     * search code path (App\Http\Controllers\Api\TranscriptController)
     * branches on `Schema::getConnection()->getDriverName()` the same way
     * this migration does, and never references `body_tsv` off SQLite.
     *
     * `segments` is `jsonb` on Postgres (queryable, compact) and a plain
     * `TEXT` column on SQLite (no native json/jsonb type) — the model casts
     * it `array` either way, so callers never see the storage difference.
     *
     * `model` is recorded on EVERY row (never nullable) — STEP-09.md's own
     * acceptance criterion: "a filler count is only comparable against
     * another from the same model, so a model upgrade must not silently
     * invalidate history."
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE speech_transcripts (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    speech_id INTEGER NOT NULL,
                    body TEXT NOT NULL DEFAULT '',
                    segments TEXT NOT NULL DEFAULT '[]',
                    word_count INTEGER NOT NULL DEFAULT 0,
                    words_per_minute REAL NULL,
                    language VARCHAR(16) NOT NULL DEFAULT 'en',
                    model VARCHAR(64) NOT NULL,
                    source VARCHAR(16) NOT NULL DEFAULT 'whisper',
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_speech_transcripts_source
                        CHECK (source IN ('whisper', 'edited')),
                    FOREIGN KEY (speech_id) REFERENCES speeches (id) ON DELETE CASCADE
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE speech_transcripts (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    speech_id BIGINT NOT NULL REFERENCES speeches (id) ON DELETE CASCADE,
                    body TEXT NOT NULL DEFAULT '',
                    segments JSONB NOT NULL DEFAULT '[]'::jsonb,
                    word_count INTEGER NOT NULL DEFAULT 0,
                    words_per_minute DOUBLE PRECISION NULL,
                    language VARCHAR(16) NOT NULL DEFAULT 'en',
                    model VARCHAR(64) NOT NULL,
                    source VARCHAR(16) NOT NULL DEFAULT 'whisper',
                    body_tsv TSVECTOR GENERATED ALWAYS AS (to_tsvector('english', body)) STORED,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_speech_transcripts_source
                        CHECK (source IN ('whisper', 'edited'))
                )
                SQL);
        }

        // One transcript per speech (§6.12: "the row" — singular, always
        // derived/replaced in place, never accumulated).
        DB::statement('CREATE UNIQUE INDEX uq_speech_transcripts_speech_id ON speech_transcripts (speech_id)');

        if ($driver !== 'sqlite') {
            DB::statement('CREATE INDEX speech_transcripts_body_tsv_gin ON speech_transcripts USING GIN (body_tsv)');
        }
    }

    public function down(): void
    {
        Schema::dropIfExists('speech_transcripts');
    }
};
