<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `data_exports` — STEP-11-FROZEN-CONTRACT.md §7. Mirrors
     * `speech_assets`' status-enum shape ("you requested something, it's
     * cooking, now it's ready"). Raw/driver-branched for the `kind`/
     * `status` CHECK constraints, same reason as every other CHECK-bearing
     * table in this schema.
     *
     * `user_id` is CASCADE (not SET NULL): an export row with no owner is
     * meaningless (nobody can ever download it, and the account-erasure
     * job never partially completes — the user row itself is never
     * hard-deleted, so this FK never actually fires in practice; it's
     * there for referential correctness, not because erasure relies on it).
     *
     * `expires_at` is nullable: set once the export is `ready` (the file
     * is not kept forever); null while `processing`/`failed`.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE data_exports (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    kind VARCHAR(24) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'processing',
                    disk VARCHAR(32) NOT NULL DEFAULT 'media',
                    path VARCHAR(255) NULL,
                    byte_size BIGINT NULL,
                    expires_at DATETIME NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_data_exports_kind
                        CHECK (kind IN ('account', 'reviewer_annotations')),
                    CONSTRAINT ck_data_exports_status
                        CHECK (status IN ('processing', 'ready', 'failed')),
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE data_exports (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    kind VARCHAR(24) NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'processing',
                    disk VARCHAR(32) NOT NULL DEFAULT 'media',
                    path VARCHAR(255) NULL,
                    byte_size BIGINT NULL,
                    expires_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_data_exports_kind
                        CHECK (kind IN ('account', 'reviewer_annotations')),
                    CONSTRAINT ck_data_exports_status
                        CHECK (status IN ('processing', 'ready', 'failed'))
                )
                SQL);
        }

        DB::statement('CREATE INDEX data_exports_user_id_created_at_index ON data_exports (user_id, created_at)');
    }

    public function down(): void
    {
        Schema::dropIfExists('data_exports');
    }
};
