<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `application_documents` — STEP-12-FROZEN-CONTRACT.md §5. Genuinely
     * new shape, not "speech_assets-shaped" reuse: `sha256` + `status`
     * (scan lifecycle) do not exist anywhere else in this schema.
     *
     * `path` is ALWAYS a randomized (`Str::uuid()`) storage key, never
     * derived from `original_filename` — the filename is stored
     * separately, display-only.
     *
     * `status` — `pending_scan -> clean | infected`, CHECK-constrained,
     * same enum-as-CHECK convention as every other status column in this
     * schema. A queued `App\Jobs\ScanApplicationDocument` (mirroring
     * `GenerateCaptions`'s shape) flips this after upload; the admin queue
     * only ever surfaces `clean` rows — `infected` rows are quarantined
     * (row kept, storage purged, status stays `infected`, never opened).
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE application_documents (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    application_id INTEGER NOT NULL,
                    disk VARCHAR(32) NOT NULL,
                    path VARCHAR(255) NOT NULL,
                    original_filename VARCHAR(255) NOT NULL,
                    byte_size BIGINT NOT NULL,
                    sha256 CHAR(64) NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending_scan',
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_application_documents_status
                        CHECK (status IN ('pending_scan', 'clean', 'infected')),
                    FOREIGN KEY (application_id) REFERENCES coach_applications (id) ON DELETE CASCADE
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE application_documents (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    application_id BIGINT NOT NULL REFERENCES coach_applications (id) ON DELETE CASCADE,
                    disk VARCHAR(32) NOT NULL,
                    path VARCHAR(255) NOT NULL,
                    original_filename VARCHAR(255) NOT NULL,
                    byte_size BIGINT NOT NULL,
                    sha256 CHAR(64) NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'pending_scan',
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_application_documents_status
                        CHECK (status IN ('pending_scan', 'clean', 'infected'))
                )
                SQL);
        }

        DB::statement('CREATE INDEX ix_application_documents_application ON application_documents (application_id)');
        DB::statement('CREATE INDEX ix_application_documents_status ON application_documents (status)');
    }

    public function down(): void
    {
        Schema::dropIfExists('application_documents');
    }
};
