<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `reviews` (MODERNIZATION_PLAN §6.3, §6.11, §7.3, §7.5).
     *
     * Same raw, driver-branched approach as `speeches`/`speech_assets` and
     * for the same reason: the `status` CHECK and the counter-cache CHECK
     * (`published_annotations_count <= annotations_count`) have no
     * Blueprint equivalent that SQLite (the test-suite driver) can acquire
     * anywhere but CREATE TABLE time.
     *
     * `speech_owner_id` is deliberately denormalized off `speeches.user_id`
     * at invite time and never re-derived: it's the inviter's speech-owner
     * identity at the moment of the invite, immutable even if the speech
     * later changes hands (it never does today, but the column exists so
     * revocation/authorization logic never needs a join back to `speeches`
     * to know who granted access). `invited_by_id` is normally the same
     * person but kept separate for admin-assisted invite attribution
     * (§7.1: an Admin can act on a speaker's behalf without becoming the
     * speech owner of record).
     *
     * `UNIQUE(speech_id, reviewer_id)` is the whole "one review row per
     * (speech, reviewer) pair" invariant — re-invitation is a service-layer
     * upsert against this same row (App\Services\ReviewService::invite),
     * never a second insert.
     *
     * `is_granting`/the partial index over it (§7.3) is explicitly
     * deferred — STEP-05 uses `status IN (...)` predicates directly
     * (Review::ACCESS_GRANTING) instead.
     *
     * No `deleted_at`, ever: a review is either revoked (tombstoned in
     * place via `revoked_at`, status untouched) or hard-deleted entirely
     * by `revokeAndPurge` — there is no soft-delete state for this table.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE reviews (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    speech_id INTEGER NOT NULL,
                    reviewer_id INTEGER NULL,
                    speech_owner_id INTEGER NOT NULL,
                    invited_by_id INTEGER NULL,
                    invitation_message VARCHAR(1000) NULL,
                    allow_preview TINYINT(1) NOT NULL DEFAULT 0,
                    prior_commentary_shared TINYINT(1) NOT NULL DEFAULT 0,
                    status VARCHAR(16) NOT NULL DEFAULT 'invited',
                    invited_at DATETIME NULL,
                    responded_at DATETIME NULL,
                    first_published_at DATETIME NULL,
                    last_published_at DATETIME NULL,
                    last_transition_at DATETIME NOT NULL,
                    revoked_at DATETIME NULL,
                    revoked_by_id INTEGER NULL,
                    revocation_reason VARCHAR(1000) NULL,
                    annotations_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
                    published_annotations_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_reviews_status
                        CHECK (status IN ('invited', 'declined', 'accepted', 'in_progress', 'published', 'abandoned')),
                    CONSTRAINT ck_reviews_counter_cache
                        CHECK (published_annotations_count <= annotations_count),
                    FOREIGN KEY (speech_id) REFERENCES speeches (id) ON DELETE CASCADE,
                    FOREIGN KEY (reviewer_id) REFERENCES users (id) ON DELETE SET NULL,
                    FOREIGN KEY (speech_owner_id) REFERENCES users (id) ON DELETE RESTRICT,
                    FOREIGN KEY (invited_by_id) REFERENCES users (id) ON DELETE SET NULL,
                    FOREIGN KEY (revoked_by_id) REFERENCES users (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE reviews (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    speech_id BIGINT NOT NULL REFERENCES speeches (id) ON DELETE CASCADE,
                    reviewer_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    speech_owner_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
                    invited_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    invitation_message VARCHAR(1000) NULL,
                    allow_preview BOOLEAN NOT NULL DEFAULT FALSE,
                    prior_commentary_shared BOOLEAN NOT NULL DEFAULT FALSE,
                    status VARCHAR(16) NOT NULL DEFAULT 'invited',
                    invited_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    responded_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    first_published_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    last_published_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    last_transition_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                    revoked_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    revoked_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    revocation_reason VARCHAR(1000) NULL,
                    annotations_count SMALLINT NOT NULL DEFAULT 0,
                    published_annotations_count SMALLINT NOT NULL DEFAULT 0,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_reviews_status
                        CHECK (status IN ('invited', 'declined', 'accepted', 'in_progress', 'published', 'abandoned')),
                    CONSTRAINT ck_reviews_counter_cache
                        CHECK (published_annotations_count <= annotations_count),
                    CONSTRAINT ck_reviews_counters_nonnegative
                        CHECK (annotations_count >= 0 AND published_annotations_count >= 0)
                )
                SQL);
        }

        DB::statement('CREATE UNIQUE INDEX uq_reviews_speech_reviewer ON reviews (speech_id, reviewer_id)');
        DB::statement('CREATE INDEX reviews_reviewer_status_last_transition_index ON reviews (reviewer_id, status, last_transition_at)');
        DB::statement('CREATE INDEX reviews_speech_status_index ON reviews (speech_id, status)');
        DB::statement('CREATE INDEX reviews_reviewer_speech_index ON reviews (reviewer_id, speech_id)');
    }

    public function down(): void
    {
        Schema::dropIfExists('reviews');
    }
};
