<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `reports` — STEP-11-FROZEN-CONTRACT.md §1. Same raw/driver-branched
     * approach as `speeches`/`reviews`/`annotations`/`speech_transcripts`:
     * `reason`/`state` are CHECK-enumerated, and SQLite (the test-suite
     * driver) can only acquire a CHECK constraint at CREATE TABLE time.
     *
     * `reportable_type`/`reportable_id` is a bare morph pair with no FK —
     * mirrors `notifications.notifiable` (Laravel's own stock morph
     * column), the established precedent in this schema for "the target
     * can be more than one model, so no single FK is possible". The
     * controller resolves `reportable_type` server-side to `Speech`/
     * `Review` only (never a client-supplied class string) — see
     * App\Http\Controllers\Api\ReportController.
     *
     * `reporter_id`/`resolved_by_id` are `ON DELETE SET NULL`: a report
     * must survive the reporter's (or resolving admin's) account being
     * erased later (STEP-11's own erasure job never touches this table),
     * the same reasoning `reviews.reviewer_id` already establishes for
     * "the record outlives the identity that produced it".
     *
     * No uniqueness constraint on (reporter_id, reportable_type,
     * reportable_id) — STEP-11.md doesn't ask for de-duplication and
     * `reports:list` printing duplicates is harmless.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE reports (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    reportable_type VARCHAR(255) NOT NULL,
                    reportable_id INTEGER NOT NULL,
                    reporter_id INTEGER NULL,
                    reason VARCHAR(32) NOT NULL,
                    detail VARCHAR(500) NULL,
                    state VARCHAR(16) NOT NULL DEFAULT 'open',
                    resolved_by_id INTEGER NULL,
                    resolved_at DATETIME NULL,
                    resolution_note VARCHAR(500) NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_reports_reason
                        CHECK (reason IN ('harassment', 'inappropriate_content', 'impersonation', 'spam', 'other')),
                    CONSTRAINT ck_reports_state
                        CHECK (state IN ('open', 'actioned', 'dismissed')),
                    FOREIGN KEY (reporter_id) REFERENCES users (id) ON DELETE SET NULL,
                    FOREIGN KEY (resolved_by_id) REFERENCES users (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE reports (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    reportable_type VARCHAR(255) NOT NULL,
                    reportable_id BIGINT NOT NULL,
                    reporter_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    reason VARCHAR(32) NOT NULL,
                    detail VARCHAR(500) NULL,
                    state VARCHAR(16) NOT NULL DEFAULT 'open',
                    resolved_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    resolved_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    resolution_note VARCHAR(500) NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_reports_reason
                        CHECK (reason IN ('harassment', 'inappropriate_content', 'impersonation', 'spam', 'other')),
                    CONSTRAINT ck_reports_state
                        CHECK (state IN ('open', 'actioned', 'dismissed'))
                )
                SQL);
        }

        // Oldest-open-first admin queue (STEP-12) / `reports:list`.
        DB::statement('CREATE INDEX reports_state_created_at_index ON reports (state, created_at)');
        DB::statement('CREATE INDEX reports_reportable_index ON reports (reportable_type, reportable_id)');
    }

    public function down(): void
    {
        Schema::dropIfExists('reports');
    }
};
