<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `audit_log` — STEP-11-FROZEN-CONTRACT.md §2. The first genuinely
     * append-only table in this schema: no `updated_at`, no soft delete,
     * no update/delete path anywhere in the model (App\Models\AuditLog
     * sets `public $timestamps = false` and casts `created_at` itself —
     * do not reach for `$table->timestamps()`/`SoftDeletes` here out of
     * habit, both would be wrong for this table).
     *
     * `action` is free text (not CHECK-enumerated) — §14's trigger list is
     * open-ended (role assignment, admin viewing, takedown, suspension,
     * deletion, export, break-glass) and several of those triggers have no
     * call site yet (STEP-12 hasn't built the admin surface). Enumerating
     * a CHECK today would either omit STEP-12's future actions or need a
     * migration to widen it later. App\Support\AuditAction is the
     * PHP-side const class giving the values STEP-11 actually writes some
     * structure without a DB-level enum.
     *
     * `subject_type`/`subject_id` mirrors `notifications.notifiable` /
     * `reports.reportable_*` — a bare morph pair, no FK.
     *
     * `metadata` is `jsonb` on Postgres, `TEXT` + array-cast on SQLite —
     * same driver split `speech_transcripts.segments` already establishes,
     * for the same reason (SQLite has no native json/jsonb type).
     *
     * `actor_id` is `ON DELETE SET NULL`: the log entry must outlive the
     * actor's account being erased later — the whole point of an audit
     * trail is that it survives the thing it recorded.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE audit_log (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    actor_id INTEGER NULL,
                    action VARCHAR(64) NOT NULL,
                    subject_type VARCHAR(255) NULL,
                    subject_id INTEGER NULL,
                    metadata TEXT NOT NULL DEFAULT '{}',
                    ip VARCHAR(45) NULL,
                    user_agent VARCHAR(255) NULL,
                    created_at DATETIME NOT NULL,
                    FOREIGN KEY (actor_id) REFERENCES users (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE audit_log (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    actor_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    action VARCHAR(64) NOT NULL,
                    subject_type VARCHAR(255) NULL,
                    subject_id BIGINT NULL,
                    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
                    ip VARCHAR(45) NULL,
                    user_agent VARCHAR(255) NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL
                )
                SQL);
        }

        DB::statement('CREATE INDEX audit_log_actor_id_created_at_index ON audit_log (actor_id, created_at)');
        DB::statement('CREATE INDEX audit_log_subject_index ON audit_log (subject_type, subject_id)');
        DB::statement('CREATE INDEX audit_log_action_created_at_index ON audit_log (action, created_at)');
    }

    public function down(): void
    {
        Schema::dropIfExists('audit_log');
    }
};
