<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `coach_applications` — STEP-12-FROZEN-CONTRACT.md §6.8. Same
     * driver-branched raw-SQL shape as `reports`
     * (2026_08_20_100001_create_reports_table.php): `status` is
     * CHECK-enumerated (sqlite, the test-suite driver, can only acquire a
     * CHECK constraint at CREATE TABLE time).
     *
     * State machine (STEP-12.md): `draft -> submitted -> under_review ->
     * approved | rejected`, and `rejected -> draft` is legal (reusing the
     * same row rather than creating a new one on reapplication).
     * `App\Models\CoachApplication`'s transition methods are the only
     * legal way this column ever changes — never a raw attribute write.
     *
     * `uq_coach_app_live` is the partial-unique-index shape
     * `2026_08_18_110002_add_voice_audio_to_annotations.php`
     * (`uq_annotations_audio_asset`) and
     * `2026_08_08_150002_create_speeches_table.php`
     * (`uq_speeches_successor`) both establish: at most one LIVE
     * application per user at a time (draft/submitted/under_review),
     * while `approved`/`rejected`/`withdrawn` rows are exempt so history
     * accumulates rather than being constrained away.
     *
     * `decided_by_id` is `ON DELETE SET NULL` — the same "the record
     * outlives the identity that produced it" reasoning `reports.
     * resolved_by_id` already establishes: a decided application must
     * survive the deciding admin's account being erased later.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE coach_applications (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id INTEGER NOT NULL,
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    statement VARCHAR(2000) NULL,
                    submitted_at DATETIME NULL,
                    decided_at DATETIME NULL,
                    decided_by_id INTEGER NULL,
                    decision_reason VARCHAR(1000) NULL,
                    documents_purge_after DATE NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    CONSTRAINT ck_coach_applications_status
                        CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'withdrawn')),
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
                    FOREIGN KEY (decided_by_id) REFERENCES users (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE coach_applications (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                    status VARCHAR(16) NOT NULL DEFAULT 'draft',
                    statement VARCHAR(2000) NULL,
                    submitted_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    decided_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    decided_by_id BIGINT NULL REFERENCES users (id) ON DELETE SET NULL,
                    decision_reason VARCHAR(1000) NULL,
                    documents_purge_after DATE NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_coach_applications_status
                        CHECK (status IN ('draft', 'submitted', 'under_review', 'approved', 'rejected', 'withdrawn'))
                )
                SQL);
        }

        DB::statement('CREATE INDEX ix_coach_app_user ON coach_applications (user_id)');
        // Oldest-submitted-first admin queue (STEP-12.md demo step 3).
        DB::statement('CREATE INDEX ix_coach_app_queue ON coach_applications (status, submitted_at)');
        DB::statement(
            'CREATE UNIQUE INDEX uq_coach_app_live ON coach_applications (user_id) '.
            "WHERE status IN ('draft', 'submitted', 'under_review')"
        );
    }

    public function down(): void
    {
        Schema::dropIfExists('coach_applications');
    }
};
