<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `annotations` (MODERNIZATION_PLAN §6.3, §8.2, §8.5). Same raw,
     * driver-branched approach as `speeches`/`speech_assets`/`reviews` and
     * for the same reason: the `kind` CHECK and the start/duration CHECK
     * have no Blueprint equivalent SQLite (the test-suite driver) can
     * acquire anywhere but CREATE TABLE time.
     *
     * `review_id NOT NULL` is structural, not incidental (§6.3's "attribution
     * is structural" and §7.3's "the review *is* the grant") — there is no
     * such thing as an annotation that doesn't belong to exactly one review.
     *
     * Soft delete (`deleted_at`) is required by the Undo affordance (§8.4,
     * built in STEP-07) but the consequence lands here already: the
     * idempotency key `UNIQUE(review_id, client_uuid)` must be scoped to
     * live rows only, or an Undo-then-recreate with the same client_uuid
     * collides against its own tombstone. Hence the partial unique index
     * below, matching the `uq_assets_primary` pattern in the speech_assets
     * migration (`WHERE is_primary` there, `WHERE deleted_at IS NULL` here).
     *
     * Both indexes lead with `review_id` per §6.3: `(review_id,
     * start_seconds)` for playback + the linear list (filter and sort in
     * one index), `(review_id, published_at)` for the speaker's published-
     * only fetch (Annotation::scopeVisibleTo).
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE annotations (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    review_id INTEGER NOT NULL,
                    client_uuid VARCHAR(36) NOT NULL,
                    body TEXT NOT NULL,
                    start_seconds NUMERIC(10, 3) NOT NULL,
                    duration_seconds NUMERIC(6, 3) NOT NULL DEFAULT 6.000,
                    kind VARCHAR(16) NOT NULL DEFAULT 'observation',
                    topic VARCHAR(32) NULL,
                    published_at DATETIME NULL,
                    lock_version INTEGER NOT NULL DEFAULT 0,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    deleted_at DATETIME NULL,
                    CONSTRAINT ck_annotations_kind
                        CHECK (kind IN ('praise', 'correction', 'observation')),
                    CONSTRAINT ck_annotations_timing
                        CHECK (start_seconds >= 0 AND duration_seconds > 0 AND duration_seconds <= 120),
                    FOREIGN KEY (review_id) REFERENCES reviews (id) ON DELETE CASCADE
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE annotations (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    review_id BIGINT NOT NULL REFERENCES reviews (id) ON DELETE CASCADE,
                    client_uuid UUID NOT NULL,
                    body TEXT NOT NULL,
                    start_seconds NUMERIC(10, 3) NOT NULL,
                    duration_seconds NUMERIC(6, 3) NOT NULL DEFAULT 6.000,
                    kind VARCHAR(16) NOT NULL DEFAULT 'observation',
                    topic VARCHAR(32) NULL,
                    published_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    lock_version INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_annotations_kind
                        CHECK (kind IN ('praise', 'correction', 'observation')),
                    CONSTRAINT ck_annotations_timing
                        CHECK (start_seconds >= 0 AND duration_seconds > 0 AND duration_seconds <= 120)
                )
                SQL);
        }

        DB::statement('CREATE INDEX annotations_review_start_index ON annotations (review_id, start_seconds)');
        DB::statement('CREATE INDEX annotations_review_published_index ON annotations (review_id, published_at)');
        DB::statement('CREATE UNIQUE INDEX uq_annotations_review_client_uuid ON annotations (review_id, client_uuid) WHERE deleted_at IS NULL');
    }

    public function down(): void
    {
        Schema::dropIfExists('annotations');
    }
};
