<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * `speeches` (MODERNIZATION_PLAN §6.3, §6.11).
     *
     * Written as raw, driver-branched SQL rather than the usual Blueprint
     * builder because two constraints here have no Blueprint equivalent in
     * this Laravel version, and — critically — SQLite (the test-suite
     * driver, per phpunit.xml) can only acquire a CHECK constraint at
     * CREATE TABLE time; `ALTER TABLE ... ADD CONSTRAINT` is not part of
     * SQLite's grammar at all. Building the whole table in one raw
     * statement per driver, instead of mixing Blueprint + a later ALTER,
     * keeps both engines' tables structurally identical rather than having
     * the constraint "stick" on Postgres and silently not exist on SQLite.
     *
     * `ck_speeches_supersedes_older` is the entire cycle defense for §6.11's
     * "supersedes" chain: identity ids are monotonic, so `supersedes_id <
     * id` makes a cycle structurally impossible without any recursive walk.
     * `uq_speeches_successor` (a partial unique index, added separately —
     * both engines support `CREATE UNIQUE INDEX ... WHERE ...` post-hoc)
     * makes the chain linear: at most one successor per attempt.
     *
     * No `visibility` column (§6.3): every speech is private by default;
     * access comes only from ownership, an access-granting review, or admin.
     */
    public function up(): void
    {
        $driver = Schema::getConnection()->getDriverName();

        if ($driver === 'sqlite') {
            DB::statement(<<<'SQL'
                CREATE TABLE speeches (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    ulid VARCHAR(26) NOT NULL,
                    user_id INTEGER NOT NULL,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(2000) NULL,
                    delivered_on DATE NULL,
                    is_example TINYINT(1) NOT NULL DEFAULT 0,
                    duration_seconds NUMERIC(10, 3) NULL,
                    playback_key VARCHAR(36) NOT NULL,
                    supersedes_id INTEGER NULL,
                    change_note VARCHAR(1000) NULL,
                    poster_time_seconds NUMERIC(10, 3) NULL,
                    created_at DATETIME NULL,
                    updated_at DATETIME NULL,
                    deleted_at DATETIME NULL,
                    CONSTRAINT ck_speeches_supersedes_older
                        CHECK (supersedes_id IS NULL OR supersedes_id < id),
                    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE RESTRICT,
                    FOREIGN KEY (supersedes_id) REFERENCES speeches (id) ON DELETE SET NULL
                )
                SQL);
        } else {
            DB::statement(<<<'SQL'
                CREATE TABLE speeches (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ulid VARCHAR(26) NOT NULL,
                    user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE RESTRICT,
                    title VARCHAR(255) NOT NULL,
                    description VARCHAR(2000) NULL,
                    delivered_on DATE NULL,
                    is_example BOOLEAN NOT NULL DEFAULT FALSE,
                    duration_seconds NUMERIC(10, 3) NULL,
                    playback_key UUID NOT NULL,
                    supersedes_id BIGINT NULL REFERENCES speeches (id) ON DELETE SET NULL,
                    change_note VARCHAR(1000) NULL,
                    poster_time_seconds NUMERIC(10, 3) NULL,
                    created_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    updated_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    deleted_at TIMESTAMP(0) WITHOUT TIME ZONE NULL,
                    CONSTRAINT ck_speeches_supersedes_older
                        CHECK (supersedes_id IS NULL OR supersedes_id < id)
                )
                SQL);
        }

        DB::statement('CREATE UNIQUE INDEX speeches_ulid_unique ON speeches (ulid)');
        DB::statement('CREATE INDEX speeches_user_id_index ON speeches (user_id)');
        DB::statement('CREATE UNIQUE INDEX uq_speeches_successor ON speeches (supersedes_id) WHERE supersedes_id IS NOT NULL');
    }

    public function down(): void
    {
        Schema::dropIfExists('speeches');
    }
};
